# Mount Google Drive

In [ ]:
#mounting google drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import Library

In [ ]:
import pandas as pd

# Memuat dan Mengeksplorasi Data

In [ ]:
# Memuat data dari file
df = pd.read_csv('/content/drive/MyDrive/DataFix/NewSeabank.csv')

In [ ]:
# Eksplorasi data
df.head() # Menampilkan beberapa baris pertama data

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,fa221cb4-62fa-4ce7-b705-cffe72fd54f9,Dika Andrian,https://play-lh.googleusercontent.com/a/ACg8oc...,sangat baik,5,0,2.73.5,2024-06-27 05:47:11,NaN,NaN,2.73.5
1,9db86960-ab95-433d-a767-cbdd1f25e481,erwin Hamdani,https://play-lh.googleusercontent.com/a/ACg8oc...,TOP,5,0,2.73.5,2024-06-27 05:42:29,NaN,NaN,2.73.5
2,432d66c7-19a7-4a6a-a40c-1d5fc23c9416,Moch Abdulloh Ibrohim,https://play-lh.googleusercontent.com/a-/ALV-U...,aplikasi ini sudah akses bagi saya yang penyan...,5,0,2.67.0,2024-06-27 05:40:50,NaN,NaN,2.67.0
3,f76f4df6-98b6-463d-b207-961a8e546397,Hasbillah Nuaina,https://play-lh.googleusercontent.com/a/ACg8oc...,mantap,5,0,2.73.5,2024-06-27 05:34:55,NaN,NaN,2.73.5
4,c91cd4b6-705f-4ca6-8ce1-c4a8cfae08b5,Karapa Rapa,https://play-lh.googleusercontent.com/a/ACg8oc...,Terbaik dan memberikan kepuasan ya bagi para p...,5,0,2.73.5,2024-06-27 05:34:01,NaN,NaN,2.73.5

In [ ]:
import pandas as pd

# Membaca dataset CSV

# Mengecek baris yang mengandung link di kolom 'content'
rows_with_links = df[df['content'].str.contains(r'http\S+|www.\S+', na=False)]

# Mengecek baris yang mengandung simbol di kolom 'content'
rows_with_symbols = df[df['content'].str.contains(r'[^\w\s]', na=False)]

# Mengecek baris yang mengandung whitespaces di kolom 'content'
rows_with_whitespaces = df[df['content'].str.contains(r'\s+', na=False)]

# Mengecek baris yang mengandung angka di kolom 'content'
rows_with_numbers = df[df['content'].str.contains(r'\d+', na=False)]

# Menampilkan hasil
print("Baris yang mengandung link di kolom 'konten_ulasan':")
print(rows_with_links[['content']])
print(f"Jumlah baris yang mengandung link: {len(rows_with_links)}\n")

print("Baris yang mengandung simbol di kolom 'content':")
print(rows_with_symbols[['content']])
print(f"Jumlah baris yang mengandung simbol: {len(rows_with_symbols)}\n")

print("Baris yang mengandung whitespaces di kolom 'content':")
print(rows_with_whitespaces[['content']])
print(f"Jumlah baris yang mengandung whitespaces: {len(rows_with_whitespaces)}\n")

print("Baris yang mengandung angka di kolom 'content':")
print(rows_with_numbers[['content']])
print(f"Jumlah baris yang mengandung angka: {len(rows_with_numbers)}\n")

# Menampilkan data dengan indeks 2494, jika ada
def check_and_print(index, df):
    if index in df.index:
        print(f"Data pada indeks {index}:")
        print(df.loc[index, 'content'])
    else:
        print(f"Data pada indeks {index} tidak ditemukan atau tidak memenuhi kondisi.\n")

Baris yang mengandung link di kolom 'konten_ulasan':
            content
1796  wawwww mantep
Jumlah baris yang mengandung link: 1

Baris yang mengandung simbol di kolom 'content':
                                                content
4     Terbaik dan memberikan kepuasan ya bagi para p...
6                  senang sekali kalo saldonya bnyak😁😁😁
7                                           toppppp....
16    sejauh ini sangat praktis dn transfer free bia...
18    Bagus dan sangat membantu untuk tranfer2, berg...
...                                                 ...
5152  mudah dipahami,, tapi cara ambil uang cash nya...
5156  mantap,ga ribet kaya bank lain,transfer gratis...
5161  bank digital dengan banyak fitur dan simpel,bu...
5169  sejauh ini ga ada masalah...aman, gampang dah ...
5172  pelayanan sangat baik & cepat. ngk kalah sama ...

[1488 rows x 1 columns]
Jumlah baris yang mengandung simbol: 1488

Baris yang mengandung whitespaces di kolom 'content':
                                                content
0                                           sangat baik
2     aplikasi ini sudah akses bagi saya yang penyan...
4     Terbaik dan memberikan kepuasan ya bagi para p...
5     saya suka buka rekening seabank trasfer lancar...
6                  senang sekali kalo saldonya bnyak😁😁😁
...                                                 ...
5169  sejauh ini ga ada masalah...aman, gampang dah ...
5170                                        sangat baik
5171                         transaksi cepat dan akurat
5172  pelayanan sangat baik & cepat. ngk kalah sama ...
5173  suku bunganya terlalu kecil dan min depositony...

[3698 rows x 1 columns]
Jumlah baris yang mengandung whitespaces: 3698

Baris yang mengandung angka di kolom 'content':
                                                content
18    Bagus dan sangat membantu untuk tranfer2, berg...
20    Sempurna banget ya sebagai alat transfer keses...
43    Dapat kan kemudahan dengan menggunakan aplikas...
71                        baru pake.. bintang 4 dulu ya
105   Habis di tf 50k ada notifikasi masuk tapi uang...
...                                                 ...
5023  Belanja di Shopee jdi potong 2k 😂😂😂 mirip kaya...
5047  Untuk Fitur si oke/mantap juga Saya punya sara...
5064                limit nya tambah doank 50 juta/hari
5111  Untuk semantara saya kasih bintang 1. Karena T...
5151  penyimpanan uang yang terbaik dan kita diberik...

[258 rows x 1 columns]
Jumlah baris yang mengandung angka: 258

In [ ]:
df.info()  # Informasi tentang tipe data dan jumlah nilai non-null dalam setiap kolom

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5174 entries, 0 to 5173
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              5174 non-null   object
 1   userName              5174 non-null   object
 2   userImage             5174 non-null   object
 3   content               5174 non-null   object
 4   score                 5174 non-null   int64
 5   thumbsUpCount         5174 non-null   int64
 6   reviewCreatedVersion  4704 non-null   object
 7   at                    5174 non-null   object
 8   replyContent          585 non-null    object
 9   repliedAt             585 non-null    object
 10  appVersion            4704 non-null   object
dtypes: int64(2), object(9)
memory usage: 444.8+ KB

# Membersihkan Kolom Data yang Tidak Dibutuhkan

In [ ]:
# Menghapus kolom yang tidak diperlukan untuk analisis
df = df.drop(columns=[
    'reviewId', 'userName', 'userImage', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion'
])
df.head()

                                             content
0                                        sangat baik
1                                                TOP
2  aplikasi ini sudah akses bagi saya yang penyan...
3                                             mantap
4  Terbaik dan memberikan kepuasan ya bagi para p...

# Menghapus Link dari Konten Review

In [ ]:
import re
# Menghapus karakter '@' dari content_remove_link
df['content_remove_at'] = df['content'].apply(lambda x: re.sub(r'@', '', str(x)))
df

,content,content_remove_at
0,sangat baik,sangat baik
1,TOP,TOP
2,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...
3,mantap,mantap
4,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...
...,...,...
5169,"sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ..."
5170,sangat baik,sangat baik
5171,transaksi cepat dan akurat,transaksi cepat dan akurat
5172,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...
5173,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...

In [ ]:
# Menghapus link dari data content
df['content_remove_link'] = df['content_remove_at'].apply(lambda x: re.sub(r'http\S+|www.\S+', '', str(x)))
df

,content,content_remove_at,content_remove_link
0,sangat baik,sangat baik,sangat baik
1,TOP,TOP,TOP
2,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...
3,mantap,mantap,mantap
4,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...
...,...,...,...
5169,"sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ..."
5170,sangat baik,sangat baik,sangat baik
5171,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat
5172,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...
5173,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...

# Menghapus Simbol - simbol dari Konten Review

In [ ]:
import re
df['content_remove_simbol'] = df['content_remove_link'].apply(lambda x: re.sub(r'[^\w\s.,!?]', '', x))
df

,content,content_remove_at,content_remove_link,content_remove_simbol
0,sangat baik,sangat baik,sangat baik,sangat baik
1,TOP,TOP,TOP,TOP
2,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...
3,mantap,mantap,mantap,mantap
4,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...
...,...,...,...,...
5169,"sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ..."
5170,sangat baik,sangat baik,sangat baik,sangat baik
5171,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat
5172,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik cepat. ngk kalah sama b...
5173,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...

# Menghapus Angka dari Konten Review

In [ ]:
# Menghapus data angka dari kolom 'content_remove_simbol' dan menyimpannya ke kolom 'content_remove_angka'
df['content_remove_angka'] = df['content_remove_simbol'].apply(lambda x: re.sub(r'\d+', '', x))

df

,content,content_remove_at,content_remove_link,content_remove_simbol,content_remove_angka
0,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik
1,TOP,TOP,TOP,TOP,TOP
2,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...
3,mantap,mantap,mantap,mantap,mantap
4,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...
...,...,...,...,...,...
5169,"sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ..."
5170,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik
5171,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat
5172,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik cepat. ngk kalah sama b...,pelayanan sangat baik cepat. ngk kalah sama b...
5173,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...

In [ ]:
def remove_extra_spaces(text):
    return re.sub(r'\s+', ' ', text)

df['content_remove_spaces'] = df['content_remove_angka'].apply(remove_extra_spaces)
df

,content,content_remove_at,content_remove_link,content_remove_simbol,content_remove_angka,content_remove_spaces
0,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik
1,TOP,TOP,TOP,TOP,TOP,TOP
2,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...
3,mantap,mantap,mantap,mantap,mantap,mantap
4,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...
...,...,...,...,...,...,...
5169,"sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ..."
5170,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik
5171,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat
5172,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik cepat. ngk kalah sama b...,pelayanan sangat baik cepat. ngk kalah sama b...,pelayanan sangat baik cepat. ngk kalah sama ba...
5173,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...

# Mengatasi Duplikat Data

In [ ]:
print(df.duplicated().sum())  # Menampilkan jumlah data duplikat

1690

In [ ]:
# Mengatasi duplikasi
df = df.drop_duplicates()

In [ ]:
print(df.duplicated().sum())  # Menampilkan jumlah data duplikat

0

# Validasi Data Setelah Pembersihan

In [ ]:
# Validasi data
df  # Memeriksa data setelah tahap pembersihan

,content,content_remove_at,content_remove_link,content_remove_simbol,content_remove_angka,content_remove_spaces
0,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik,sangat baik
1,TOP,TOP,TOP,TOP,TOP,TOP
2,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...,aplikasi ini sudah akses bagi saya yang penyan...
3,mantap,mantap,mantap,mantap,mantap,mantap
4,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...,Terbaik dan memberikan kepuasan ya bagi para p...
...,...,...,...,...,...,...
5167,simple gratis,simple gratis,simple gratis,simple gratis,simple gratis,simple gratis
5169,"sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ...","sejauh ini ga ada masalah...aman, gampang dah ..."
5171,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat,transaksi cepat dan akurat
5172,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik & cepat. ngk kalah sama ...,pelayanan sangat baik cepat. ngk kalah sama b...,pelayanan sangat baik cepat. ngk kalah sama b...,pelayanan sangat baik cepat. ngk kalah sama ba...
5173,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...,suku bunganya terlalu kecil dan min depositony...

In [ ]:
# Ambil hanya kolom 'content_remove_spaces'
df = df[['content_remove_spaces']]
df

                                  content_remove_spaces
0                                           sangat baik
1                                                   TOP
2     aplikasi ini sudah akses bagi saya yang penyan...
3                                                mantap
4     Terbaik dan memberikan kepuasan ya bagi para p...
...                                                 ...
5167                                      simple gratis
5169  sejauh ini ga ada masalah...aman, gampang dah ...
5171                         transaksi cepat dan akurat
5172  pelayanan sangat baik cepat. ngk kalah sama ba...
5173  suku bunganya terlalu kecil dan min depositony...

[3484 rows x 1 columns]

In [ ]:
# Mengganti nama kolom untuk konten yang telah dibersihkan
df = df.rename(columns={'content_remove_spaces': 'content'})

In [ ]:
df

                                                content
0                                           sangat baik
1                                                   TOP
2     aplikasi ini sudah akses bagi saya yang penyan...
3                                                mantap
4     Terbaik dan memberikan kepuasan ya bagi para p...
...                                                 ...
5167                                      simple gratis
5169  sejauh ini ga ada masalah...aman, gampang dah ...
5171                         transaksi cepat dan akurat
5172  pelayanan sangat baik cepat. ngk kalah sama ba...
5173  suku bunganya terlalu kecil dan min depositony...

[3484 rows x 1 columns]

In [ ]:
# Memeriksa total data setelah menghapus tanda baca dan spasi tambahan
total_data = df.shape[0]
print("Total data setelah penghapusan tanda baca dan spasi tambahan:", total_data)

Total data setelah penghapusan tanda baca dan spasi tambahan: 3484

# Menyimpan Data yang Telah Dibersihkan

In [ ]:
# Menyimpan data yang telah dibersihkan
df.to_csv('/content/drive/MyDrive/DataFix/CleanedSeabank.csv', index=False)